[2024-02-13T01:27:07.948+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.second_task manual__2024-02-13T01:27:05.825219+00:00 [queued]>
[2024-02-13T01:27:07.955+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.second_task manual__2024-02-13T01:27:05.825219+00:00 [queued]>
[2024-02-13T01:27:07.955+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-13T01:27:07.973+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): second_task> on 2024-02-13 01:27:05.825219+00:00
[2024-02-13T01:27:07.981+0000] {standard_task_runner.py:60} INFO - Started process 801 to run task
[2024-02-13T01:27:07.984+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'second_task', 'manual__2024-02-13T01:27:05.825219+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp_oo3tx02']
[2024-02-13T01:27:07.985+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask second_task
[2024-02-13T01:27:08.047+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v4.second_task manual__2024-02-13T01:27:05.825219+00:00 [running]> on host e97f82a89325
[2024-02-13T01:27:08.144+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shiv' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T01:27:05.825219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-13T01:27:05.825219+00:00'
[2024-02-13T01:27:08.145+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-13T01:27:08.145+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo I am the second one here!']
[2024-02-13T01:27:08.162+0000] {subprocess.py:86} INFO - Output:
[2024-02-13T01:27:08.164+0000] {subprocess.py:93} INFO - I am the second one here!
[2024-02-13T01:27:08.165+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-13T01:27:08.214+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=second_task, execution_date=20240213T012705, start_date=20240213T012707, end_date=20240213T012708
[2024-02-13T01:27:08.243+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-13T01:27:08.271+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
