[2024-02-14T03:49:02.105+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v01.get_name scheduled__2021-10-26T00:00:00+00:00 [queued]>
[2024-02-14T03:49:02.213+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_api_v01.get_name scheduled__2021-10-26T00:00:00+00:00 [queued]>
[2024-02-14T03:49:02.219+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-14T03:49:02.356+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): get_name> on 2021-10-26 00:00:00+00:00
[2024-02-14T03:49:02.457+0000] {standard_task_runner.py:60} INFO - Started process 898 to run task
[2024-02-14T03:49:02.485+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_api_v01', 'get_name', 'scheduled__2021-10-26T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmpqc8if9nj']
[2024-02-14T03:49:02.493+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask get_name
[2024-02-14T03:49:03.134+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_taskflow_api_v01.get_name scheduled__2021-10-26T00:00:00+00:00 [running]> on host e97f82a89325
[2024-02-14T03:49:04.319+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Shiv' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_api_v01' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2021-10-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-26T00:00:00+00:00'
[2024-02-14T03:49:04.330+0000] {python.py:201} INFO - Done. Returned value was: Jerry
[2024-02-14T03:49:04.670+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_api_v01, task_id=get_name, execution_date=20211026T000000, start_date=20240214T034902, end_date=20240214T034904
[2024-02-14T03:49:04.927+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-14T03:49:05.119+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
