[2024-02-27T04:13:45.829+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v08.delete_data_from_table scheduled__2024-02-24T00:00:00+00:00 [queued]>
[2024-02-27T04:13:45.997+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v08.delete_data_from_table scheduled__2024-02-24T00:00:00+00:00 [queued]>
[2024-02-27T04:13:45.999+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-27T04:13:46.141+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2024-02-24 00:00:00+00:00
[2024-02-27T04:13:46.169+0000] {standard_task_runner.py:60} INFO - Started process 84 to run task
[2024-02-27T04:13:46.190+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v08', 'delete_data_from_table', 'scheduled__2024-02-24T00:00:00+00:00', '--job-id', '482', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmptukimian']
[2024-02-27T04:13:46.216+0000] {standard_task_runner.py:88} INFO - Job 482: Subtask delete_data_from_table
[2024-02-27T04:13:47.048+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v08.delete_data_from_table scheduled__2024-02-24T00:00:00+00:00 [running]> on host f592a0b4b395
[2024-02-27T04:13:48.056+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Shiv' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v08' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-24T00:00:00+00:00'
[2024-02-27T04:13:48.063+0000] {sql.py:276} INFO - Executing: 
            DELETE FROM dag_runs WHERE dt = '2024-02-24' and dag_id = 'dag_with_postgres_operator_v08';
        
[2024-02-27T04:13:48.160+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-02-27T04:13:48.309+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-02-27T04:13:48.325+0000] {sql.py:450} INFO - Running statement: 
            DELETE FROM dag_runs WHERE dt = '2024-02-24' and dag_id = 'dag_with_postgres_operator_v08';
        , parameters: None
[2024-02-27T04:13:48.522+0000] {sql.py:459} INFO - Rows affected: 0
[2024-02-27T04:13:48.544+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v08, task_id=delete_data_from_table, execution_date=20240224T000000, start_date=20240227T041345, end_date=20240227T041348
[2024-02-27T04:13:48.808+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-27T04:13:49.093+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
