[2024-02-19T18:30:00.261+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v08.delete_data_from_table scheduled__2024-02-13T00:00:00+00:00 [queued]>
[2024-02-19T18:30:00.287+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v08.delete_data_from_table scheduled__2024-02-13T00:00:00+00:00 [queued]>
[2024-02-19T18:30:00.287+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-02-19T18:30:00.316+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2024-02-13 00:00:00+00:00
[2024-02-19T18:30:00.334+0000] {standard_task_runner.py:60} INFO - Started process 1170 to run task
[2024-02-19T18:30:00.346+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v08', 'delete_data_from_table', 'scheduled__2024-02-13T00:00:00+00:00', '--job-id', '454', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmprwtms73u']
[2024-02-19T18:30:00.348+0000] {standard_task_runner.py:88} INFO - Job 454: Subtask delete_data_from_table
[2024-02-19T18:30:00.798+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v08.delete_data_from_table scheduled__2024-02-13T00:00:00+00:00 [running]> on host 55ac849b3b96
[2024-02-19T18:30:01.023+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Shiv' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v08' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-13T00:00:00+00:00'
[2024-02-19T18:30:01.027+0000] {sql.py:276} INFO - Executing: 
            DELETE FROM dag_runs WHERE dt = '2024-02-13' and dag_id = 'dag_with_postgres_operator_v08';
        
[2024-02-19T18:30:01.115+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-02-19T18:30:01.248+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-02-19T18:30:01.260+0000] {sql.py:450} INFO - Running statement: 
            DELETE FROM dag_runs WHERE dt = '2024-02-13' and dag_id = 'dag_with_postgres_operator_v08';
        , parameters: None
[2024-02-19T18:30:01.287+0000] {sql.py:459} INFO - Rows affected: 0
[2024-02-19T18:30:01.319+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v08, task_id=delete_data_from_table, execution_date=20240213T000000, start_date=20240219T183000, end_date=20240219T183001
[2024-02-19T18:30:01.503+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-19T18:30:01.549+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
